---
name: Setup Brainfuck
author: Yevhen Fabizhevskyi
description: 'This GitHub action installs one of the brainfuck interpreters called brainfucky'
branding:
  icon: chevrons-right
  color: gray-dark
inputs:
  version:
    description: 'Brainfucky library version'
    required: false
    default: '0.1.dev1'
runs:
  using: 'composite'
  steps:
    - name: Install Brainfuck
      run: pip3 install brainfucky==${{ inputs.version }}
      shell: bash
