---
name: Functional Tests

on:
  push:
    branches:
      - 'main'
      - 'bugfix/**'
      - 'bump/patch-*'
      - 'feature/**'

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  functional_tests:
    name: Run script
    timeout-minutes: 5
    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest']
        version: ['0.1.dev0', '0.1.dev1']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.4
        with:
          ref: ${{ github.ref }}
      - uses: ./
        with:
          version: ${{ matrix.version }}
      - name: Validate command (non-Windows)
        if: ${{ matrix.os != 'windows-latest' }}
        run: |
          touch ./hello-world.bf
          echo "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.++" > ./hello-world.bf
          echo "+.------.--------.>>+.>++." >> ./hello-world.bf
          output=$(brainfucky --file ./hello-world.bf)
          rm ./hello-world.bf
          [[ "${output:32:12}" == "Hello World!" ]] || exit 1;
        shell: bash
      - name: Validate command (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          New-Item -Path . -Name "hello-world.bf" -ItemType "file" -Value "++++++++[>++++[>++>+++>+++>+<<<<-]>+>+>->>+[<]<-]>>.>---.+++++++..+++.>>.<-.<.++`n+.------.--------.>>+.>++."
          $Output = (brainfucky --file ./hello-world.bf) | Out-String
          Remove-Item hello-world.bf
          &{If($Output.Substring(33, 12) -ne 'Hello World!') {exit 1}}
        shell: pwsh
